variable "region" {}
variable "gcp_project" {}
variable "credentials" {}
variable "vpc-name" {}
variable "subnet-name" {}
variable "firewall-name" {}
variable "subnet_cidr" {}
variable "instance_name" {}
variable "machine_type" {}
variable "image" {}
variable "zone" {}
