variable "region" {}
variable "gcp_project" {}
variable "credentials" {}
variable "name" {}
variable "subnet_cidr" {}
variable "instance_name" {}
variable "machine_type" {}
variable "image" {}
variable "zone" {}
